// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfO7-_iAjTG-WauptCemdXgz_NytduMpA',
    appId: '1:959613903533:web:b7fd96127ca414ab77dc24',
    messagingSenderId: '959613903533',
    projectId: 'rafflemobileapp',
    authDomain: 'rafflemobileapp.firebaseapp.com',
    storageBucket: 'rafflemobileapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejiYFzOrlZpwql4q0zGqL15TDB8Fu_Bo',
    appId: '1:959613903533:android:f2c632e1576110f077dc24',
    messagingSenderId: '959613903533',
    projectId: 'rafflemobileapp',
    storageBucket: 'rafflemobileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBknT2SzN4I8lMEsILw2THrj3yG12iNIaY',
    appId: '1:959613903533:ios:a53b60b6156b132177dc24',
    messagingSenderId: '959613903533',
    projectId: 'rafflemobileapp',
    storageBucket: 'rafflemobileapp.appspot.com',
    iosClientId: '959613903533-houofvl989d7gdqe1m5dsq3l2d2mgob7.apps.googleusercontent.com',
    iosBundleId: 'com.example.raffleMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBknT2SzN4I8lMEsILw2THrj3yG12iNIaY',
    appId: '1:959613903533:ios:a53b60b6156b132177dc24',
    messagingSenderId: '959613903533',
    projectId: 'rafflemobileapp',
    storageBucket: 'rafflemobileapp.appspot.com',
    iosClientId: '959613903533-houofvl989d7gdqe1m5dsq3l2d2mgob7.apps.googleusercontent.com',
    iosBundleId: 'com.example.raffleMobileApp',
  );
}
